<style>

    /* 
        VERMELHO : #da1f28

    */

    body > header {
        padding: 20px 0px;
        background: url('http://netpchost.tec.br/storage/app/imagens/d01fc45b2d8e78f614dd0e3b21a95743.jpeg'); 
        background-size: cover;
    }

    body > header img{
        width: 250px;
    }

    body > header li {
        list-style-type: none;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        height: 100%;
        width: 100%;
    }

    body > header li a {
        color: #da1f28;
        font-weight: bold;
        font-size: 18px;
    }

</style>